### ISSUE TITLE
silabs-firmware-builder add EFR32MG21A020F512IM32 support

### ISSUE THREAD

**Issue by zalatnaicsongor** [Nerivec/SmartHomeEnhanced#2]
Hi, sorry for getting in touch with you in this repo, the relevant repo didn't have issues enabled.
I'd like to add EFR32MG21A020F512IM32 (xiaomi Mi-Smart-Hub-2-Pro lumi-gateway-mgl001) support to your `silabs-firmware-builder`. In order to do that, first I'd like to understand how you generated the [rcp-uart-802154-blehci_EFR32MG21A020F768IM32](https://github.com/Nerivec/silabs-firmware-builder/tree/main/src/rcp-uart-802154-blehci_EFR32MG21A020F768IM32) *_EFR32MG21A020F768IM32 project. I'd like to do the same (I have simplicity studio & the required SDK installed) for the EFR32MG21A020F512IM32 chip. Firmwares compiled for the EFR32MG21A020F768IM32 version do not work on the 512 one.

**Comment by Nerivec** [comment]
Since it's EFR32MG21A020F, it should work fine in Github workflow by just supplying an extra manifest for that device, the builder takes care of retrieving the proper files for 512/768/1024 as directed by the manifest. For example [this one](https://github.com/Nerivec/silabs-firmware-builder/blob/main/manifests/nabucasa_skyconnect_ncp-uart-hw_115200.yaml) vs [this one](https://github.com/Nerivec/silabs-firmware-builder/blob/main/manifests/sonoff_zbdonglee_ncp-uart-sw_115200.yaml), same project files, but configured with the proper pins & other details in the manifest.

**Comment by zalatnaicsongor** [comment]
Found it, thanks: https://github.com/Nerivec/silabs-firmware-builder/blob/main/tools/build_project.py#L311
